<a href="https://colab.research.google.com/github/CookiesAndWater/MAT_422/blob/main/MAT422_1_2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Chapter 1.2


##1.2.1 Linear Spaces

Definitions:


*   **Linear Combination**: A vector made from a subset by a combination of differently scaled vectors and combining them. This results in a linear combination.
*   **Linear Subpace**: A linear subspace is made up by linear combinations. The requirements for it to be a linear subspace is that a linear subsapce of V is a subset U ⊆ V and is both closed under vecotr addition and scalar multiplication. This can be represented in the form $u_{1},u_{2} ∈U$ and $αu_{1}\in U$


In [ ]:
import numpy as np

#Example of Linear Combination

v1 = np.array([1,2,3])
v2 = np.array([11,22,33])

a1 = 7
a2 = 3

#Adding them results in a new vector
new_vector = (a1 * v1) + (a2 + v2)
print(new_vector)

[21 39 57]


In the code above, there are two vectors, v1 and v2. Also, there are two scalar values, a1 and a2. The new vector(printed above) is made from a linear combination of v1 scaled by a1 combined with v2 scaled by v2.

*   **Span**: The set of all possible vectors that can be made from linear combinations
*   **Linear Independence**: A set of vectors that cannot be made by a linear combination of the other vectors.
*   **Basis**: A set of vectors that both span U(the linear subspace of V) and are linearly independent.



##1.2.2 Orthogonality



*   **Inner Product**: ⟨u,v⟩, which is an abreviation of the dot product.
*   **Norm**: ||u||, which is a variation of the inner product, written in the form  $(∑_{1}^{n}u_{i}^{2})^{1/2}$
*   **Orthonormal**: A list of vectors is orthonormal if they have have a magnitude of 1 and are mutually orthogonal.





In [66]:
v1 = np.array([1,4,5])
v2 = np.array([1,3,5])

#Inner product example
inner = np.dot(v1,v2)
print("The inner product for v1 and v2 is: ")
print(inner, "\n")

#Norm example
norm = np.dot(v1,v1)
print("The norm is for v1: ")
print(norm, "\n")

#Orthonormal Example
orthonormal_matrix = np.array([
[1,0,],
[0,1,]
])

print("The orthornormal matrix is: \n", orthonormal_matrix)

The inner product for v1 and v2 is: 
38 

The norm is for v1: 
42 

The orthornormal matrix is: 
 [[1 0]
 [0 1]]


Norm is calculated by the dot product of two vectors, specifically v1 and v2. Inner product is calculated from the dot product of itself. The matrix shown above is orthonormal, since it has a magnitude of 1 and is mutually orthogonal

* **Orthogonal Projection**: Letting U ⊆ V with orthonormal basis, the orthogonal projection of v ∈ V on U is define by $P_{U}v = ∑_{j=1}^{m}⟨v,q_{j}⟩q_{j}$


##1.2.3 Gram-Schmidt Process

* **Gram-Shmidt**: A process that turns of turning linearly independent vectors into orthonormal vectors that cover the same span. In simpler terms, it finds a orthornaml basis from a basis.
* **Projection operator**: It is defined by the equation $proj_{u}(v) = \frac{⟨u,v⟩}{⟨u,u⟩}u$

##1.2.4 EigenValues and Eigenvectors



*   **Eigenvalue**: λ ∈ ℜ is called an eigenvalue of A if there is a nonzero vector x, where x ≠ 0, in the equation Ax = λx.
*  **Eigenvector**: The vector x in the equation, Ax = λx, represents the eigenvector.
* **Trace**: The trace of A, is the sum of it's diagnonal entries of the matrix, which is also the sum of all eigenvalues.
* **Determinant**: A unique value of a square matrices. The way of finding this value depends on the size of the matrix, but can be found from the product of its eigenvalues.



In [ ]:
#Example of eigenvalues and eigenvectors
A = np.array([
[3,2,4],
[2,0,2],
[4,2,3]
])

eigenvalues, eigenvectors = np.linalg.eig(a)
print("The eigenvalues are:",eigenvalues)
print("The eigenvectors are:\n",eigenvectors)

#Trace example
sum_of_eigval = 0
for i in eigenvalues:
    sum_of_eigval += i

diag = np.diag(A)
trace = 0
for i in diag:
  trace += i
print("\nThe trace is: ",trace, ", while the sum of eigenvalues is: ",sum_of_eigval)

#Determinent example
determinent = np.linalg.det(A)
product_of_eigval = 1
for i in eigenvalues:
  product_of_eigval *= i
print("The determinent is: ", determinent, " while the product of eigenvalues is: ", product_of_eigval)

The eigenvalues are: [-1.  8. -1.]
The eigenvectors are:
 [[-0.74535599  0.66666667 -0.21539222]
 [ 0.2981424   0.33333333 -0.77010996]
 [ 0.59628479  0.66666667  0.6004472 ]]

The trace is:  6 , while the sum of eigenvalues is:  5.999999999999999
The determinent is:  7.999999999999998  while the product of eigenvalues is:  8.000000000000005


The code above gives the eigenvalues and eiganvectors corresponding to the variable A above. Also above, the trace and sum of the eigenvalues are the same, while the determinent and product of the eigenvalues are the same(the numbers are different due to floating point calculation).

* Diagonalization: There exists a nonsingular matrix P such that $A = PDP^{-1}$.
 * P represents an orthogonal matrix that is invertible, where $P^{-1} = P^{T}$.
 * D represents a diagonal matrix, where only the diagonal of the matrix can contain non-zero numbers.






In [56]:
#Example of diagonalization

A = np.array([
    [2,0,0],
    [1,2,1],
    [-1,0,1]
])

D = np.array([
    [2,0,0],
    [0,2,0],
    [0,0,1]
])

P = np.array([
    [0,-1,0],
    [1,0,-1],
    [0,1,1]
])

P_D_invP = np.matmul(np.matmul(P,D),(np.linalg.inv(P)))

print("The matrix A: \n", A, "\nis equivalent to PDP^-1: \n",P_D_invP)


The matrix A: 
 [[ 2  0  0]
 [ 1  2  1]
 [-1  0  1]] 
is equivalent to PDP^-1: 
 [[ 2.  0.  0.]
 [ 1.  2.  1.]
 [-1.  0.  1.]]
[[ 0 -1  0]
 [ 1  0 -1]
 [ 0  1  1]]


The first matrix is the matrix A. The second matrix is a matrix combined from $PDP^{-1}$. P is gotten from both the eigenvalues and eigen vectors. D is the eigenvalues made into the diagonal of matrix D.